select * from topics where subject_id = 1
-- INSERT into topics(subject_id, topic_name) values (1,"Diseases, Immunity, Drugs");
-- INSERT into topics(subject_id, topic_name) values (1,"Plant Nutrition");
-- INSERT into topics(subject_id, topic_name) values (1,"Human Nutrition");
-- INSERT into topics(subject_id, topic_name) values (1,"Biological Molecules");
-- INSERT into topics(subject_id, topic_name) values (1,"Enzymes");
-- INSERT into topics(subject_id, topic_name) values (1,"Excretion in Humans");
-- INSERT into topics(subject_id, topic_name) values (1,"Classification of Organisms");
-- INSERT into topics(subject_id, topic_name) values (1,"Coordination and Response");
-- INSERT INTO topics (subject_id, topic_name) 
-- VALUES (1, 'Movement of Substances in and out of Cells');